# Generated by Django 4.2.4 on 2023-08-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_schooldocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldocuments',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chat'),
            preserve_default=False,
        ),
    ]
