# Generated by Django 4.2.4 on 2023-09-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='whatsapp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
