# Generated by Django 4.2.4 on 2023-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chat_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateTimeField(default=None,null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_days',
            field=models.IntegerField(default=5),
        ),
    ]
