# Generated by Django 4.2.4 on 2023-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_profile_subscription_end_date_profile_trial_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
