# Generated by Django 4.2.4 on 2023-10-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_profile_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_end_date',
        ),
    ]
