# Generated by Django 4.2.6 on 2023-10-23 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0013_profile_subscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterwaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('encryption_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.TextField()),
                ('complete', models.BooleanField()),
                ('number_of_days', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
