# Generated by Django 4.2.6 on 2023-10-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_flutterwavedetails_transactionsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutterwavedetails',
            name='secret_hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flutterwavedetails',
            name='encryption_key',
            field=models.TextField(null=True),
        ),
    ]
