# Generated by Django 4.2.6 on 2023-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_flutterwavedetails_secret_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsdetails',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionsdetails',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
